name: spacetraders

services:
  postgresql:
    image: bitnami/postgresql:15
    volumes:
      - postgresql-data:/bitnami/postgresql
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    environment:
      POSTGRESQL_DATABASE: spacetraders
      POSTGRESQL_USERNAME: spacetraders
      ALLOW_EMPTY_PASSWORD: yes
volumes:
  postgresql-data:
