/*
SpaceTraders API

SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.

API version: 2.0.0
Contact: joel@spacetraders.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// FactionTraitSymbol The unique identifier of the trait.
type FactionTraitSymbol string

// List of FactionTraitSymbol
const (
	FACTION_TRAIT_BUREAUCRATIC             FactionTraitSymbol = "BUREAUCRATIC"
	FACTION_TRAIT_SECRETIVE                FactionTraitSymbol = "SECRETIVE"
	FACTION_TRAIT_CAPITALISTIC             FactionTraitSymbol = "CAPITALISTIC"
	FACTION_TRAIT_INDUSTRIOUS              FactionTraitSymbol = "INDUSTRIOUS"
	FACTION_TRAIT_PEACEFUL                 FactionTraitSymbol = "PEACEFUL"
	FACTION_TRAIT_DISTRUSTFUL              FactionTraitSymbol = "DISTRUSTFUL"
	FACTION_TRAIT_WELCOMING                FactionTraitSymbol = "WELCOMING"
	FACTION_TRAIT_SMUGGLERS                FactionTraitSymbol = "SMUGGLERS"
	FACTION_TRAIT_SCAVENGERS               FactionTraitSymbol = "SCAVENGERS"
	FACTION_TRAIT_REBELLIOUS               FactionTraitSymbol = "REBELLIOUS"
	FACTION_TRAIT_EXILES                   FactionTraitSymbol = "EXILES"
	FACTION_TRAIT_PIRATES                  FactionTraitSymbol = "PIRATES"
	FACTION_TRAIT_RAIDERS                  FactionTraitSymbol = "RAIDERS"
	FACTION_TRAIT_CLAN                     FactionTraitSymbol = "CLAN"
	FACTION_TRAIT_GUILD                    FactionTraitSymbol = "GUILD"
	FACTION_TRAIT_DOMINION                 FactionTraitSymbol = "DOMINION"
	FACTION_TRAIT_FRINGE                   FactionTraitSymbol = "FRINGE"
	FACTION_TRAIT_FORSAKEN                 FactionTraitSymbol = "FORSAKEN"
	FACTION_TRAIT_ISOLATED                 FactionTraitSymbol = "ISOLATED"
	FACTION_TRAIT_LOCALIZED                FactionTraitSymbol = "LOCALIZED"
	FACTION_TRAIT_ESTABLISHED              FactionTraitSymbol = "ESTABLISHED"
	FACTION_TRAIT_NOTABLE                  FactionTraitSymbol = "NOTABLE"
	FACTION_TRAIT_DOMINANT                 FactionTraitSymbol = "DOMINANT"
	FACTION_TRAIT_INESCAPABLE              FactionTraitSymbol = "INESCAPABLE"
	FACTION_TRAIT_INNOVATIVE               FactionTraitSymbol = "INNOVATIVE"
	FACTION_TRAIT_BOLD                     FactionTraitSymbol = "BOLD"
	FACTION_TRAIT_VISIONARY                FactionTraitSymbol = "VISIONARY"
	FACTION_TRAIT_CURIOUS                  FactionTraitSymbol = "CURIOUS"
	FACTION_TRAIT_DARING                   FactionTraitSymbol = "DARING"
	FACTION_TRAIT_EXPLORATORY              FactionTraitSymbol = "EXPLORATORY"
	FACTION_TRAIT_RESOURCEFUL              FactionTraitSymbol = "RESOURCEFUL"
	FACTION_TRAIT_FLEXIBLE                 FactionTraitSymbol = "FLEXIBLE"
	FACTION_TRAIT_COOPERATIVE              FactionTraitSymbol = "COOPERATIVE"
	FACTION_TRAIT_UNITED                   FactionTraitSymbol = "UNITED"
	FACTION_TRAIT_STRATEGIC                FactionTraitSymbol = "STRATEGIC"
	FACTION_TRAIT_INTELLIGENT              FactionTraitSymbol = "INTELLIGENT"
	FACTION_TRAIT_RESEARCH_FOCUSED         FactionTraitSymbol = "RESEARCH_FOCUSED"
	FACTION_TRAIT_COLLABORATIVE            FactionTraitSymbol = "COLLABORATIVE"
	FACTION_TRAIT_PROGRESSIVE              FactionTraitSymbol = "PROGRESSIVE"
	FACTION_TRAIT_MILITARISTIC             FactionTraitSymbol = "MILITARISTIC"
	FACTION_TRAIT_TECHNOLOGICALLY_ADVANCED FactionTraitSymbol = "TECHNOLOGICALLY_ADVANCED"
	FACTION_TRAIT_AGGRESSIVE               FactionTraitSymbol = "AGGRESSIVE"
	FACTION_TRAIT_IMPERIALISTIC            FactionTraitSymbol = "IMPERIALISTIC"
	FACTION_TRAIT_TREASURE_HUNTERS         FactionTraitSymbol = "TREASURE_HUNTERS"
	FACTION_TRAIT_DEXTEROUS                FactionTraitSymbol = "DEXTEROUS"
	FACTION_TRAIT_UNPREDICTABLE            FactionTraitSymbol = "UNPREDICTABLE"
	FACTION_TRAIT_BRUTAL                   FactionTraitSymbol = "BRUTAL"
	FACTION_TRAIT_FLEETING                 FactionTraitSymbol = "FLEETING"
	FACTION_TRAIT_ADAPTABLE                FactionTraitSymbol = "ADAPTABLE"
	FACTION_TRAIT_SELF_SUFFICIENT          FactionTraitSymbol = "SELF_SUFFICIENT"
	FACTION_TRAIT_DEFENSIVE                FactionTraitSymbol = "DEFENSIVE"
	FACTION_TRAIT_PROUD                    FactionTraitSymbol = "PROUD"
	FACTION_TRAIT_DIVERSE                  FactionTraitSymbol = "DIVERSE"
	FACTION_TRAIT_INDEPENDENT              FactionTraitSymbol = "INDEPENDENT"
	FACTION_TRAIT_SELF_INTERESTED          FactionTraitSymbol = "SELF_INTERESTED"
	FACTION_TRAIT_FRAGMENTED               FactionTraitSymbol = "FRAGMENTED"
	FACTION_TRAIT_COMMERCIAL               FactionTraitSymbol = "COMMERCIAL"
	FACTION_TRAIT_FREE_MARKETS             FactionTraitSymbol = "FREE_MARKETS"
	FACTION_TRAIT_ENTREPRENEURIAL          FactionTraitSymbol = "ENTREPRENEURIAL"
)

// All allowed values of FactionTraitSymbol enum
var AllowedFactionTraitSymbolEnumValues = []FactionTraitSymbol{
	"BUREAUCRATIC",
	"SECRETIVE",
	"CAPITALISTIC",
	"INDUSTRIOUS",
	"PEACEFUL",
	"DISTRUSTFUL",
	"WELCOMING",
	"SMUGGLERS",
	"SCAVENGERS",
	"REBELLIOUS",
	"EXILES",
	"PIRATES",
	"RAIDERS",
	"CLAN",
	"GUILD",
	"DOMINION",
	"FRINGE",
	"FORSAKEN",
	"ISOLATED",
	"LOCALIZED",
	"ESTABLISHED",
	"NOTABLE",
	"DOMINANT",
	"INESCAPABLE",
	"INNOVATIVE",
	"BOLD",
	"VISIONARY",
	"CURIOUS",
	"DARING",
	"EXPLORATORY",
	"RESOURCEFUL",
	"FLEXIBLE",
	"COOPERATIVE",
	"UNITED",
	"STRATEGIC",
	"INTELLIGENT",
	"RESEARCH_FOCUSED",
	"COLLABORATIVE",
	"PROGRESSIVE",
	"MILITARISTIC",
	"TECHNOLOGICALLY_ADVANCED",
	"AGGRESSIVE",
	"IMPERIALISTIC",
	"TREASURE_HUNTERS",
	"DEXTEROUS",
	"UNPREDICTABLE",
	"BRUTAL",
	"FLEETING",
	"ADAPTABLE",
	"SELF_SUFFICIENT",
	"DEFENSIVE",
	"PROUD",
	"DIVERSE",
	"INDEPENDENT",
	"SELF_INTERESTED",
	"FRAGMENTED",
	"COMMERCIAL",
	"FREE_MARKETS",
	"ENTREPRENEURIAL",
}

func (v *FactionTraitSymbol) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := FactionTraitSymbol(value)
	for _, existing := range AllowedFactionTraitSymbolEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid FactionTraitSymbol", value)
}

// NewFactionTraitSymbolFromValue returns a pointer to a valid FactionTraitSymbol
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewFactionTraitSymbolFromValue(v string) (*FactionTraitSymbol, error) {
	ev := FactionTraitSymbol(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for FactionTraitSymbol: valid values are %v", v, AllowedFactionTraitSymbolEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v FactionTraitSymbol) IsValid() bool {
	for _, existing := range AllowedFactionTraitSymbolEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to FactionTraitSymbol value
func (v FactionTraitSymbol) Ptr() *FactionTraitSymbol {
	return &v
}

type NullableFactionTraitSymbol struct {
	value *FactionTraitSymbol
	isSet bool
}

func (v NullableFactionTraitSymbol) Get() *FactionTraitSymbol {
	return v.value
}

func (v *NullableFactionTraitSymbol) Set(val *FactionTraitSymbol) {
	v.value = val
	v.isSet = true
}

func (v NullableFactionTraitSymbol) IsSet() bool {
	return v.isSet
}

func (v *NullableFactionTraitSymbol) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFactionTraitSymbol(val *FactionTraitSymbol) *NullableFactionTraitSymbol {
	return &NullableFactionTraitSymbol{value: val, isSet: true}
}

func (v NullableFactionTraitSymbol) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFactionTraitSymbol) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
