//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type MarketProbes struct {
	Ship     string `sql:"primary_key"`
	Waypoint string `sql:"primary_key"`
	System   string
}
