//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type RasterOverviews struct {
	OTableCatalog  *string
	OTableSchema   *string
	OTableName     *string
	ORasterColumn  *string
	RTableCatalog  *string
	RTableSchema   *string
	RTableName     *string
	RRasterColumn  *string
	OverviewFactor *int32
}
