//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type RasterColumns struct {
	RTableCatalog   *string
	RTableSchema    *string
	RTableName      *string
	RRasterColumn   *string
	Srid            *int32
	ScaleX          *float64
	ScaleY          *float64
	BlocksizeX      *int32
	BlocksizeY      *int32
	SameAlignment   *bool
	RegularBlocking *bool
	NumBands        *int32
	PixelTypes      *string
	NodataValues    *string
	OutDb           *string
	Extent          *string
	SpatialIndex    *bool
}
