//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Ships struct {
	ID           string `sql:"primary_key"`
	ArrivalAt    time.Time
	DepartedAt   time.Time
	Waypoint     string
	System       string
	Status       string
	Destination  string
	Origin       string
	MaxFuel      int32
	CurrentFuel  int32
	MaxCargo     int32
	CurrentCargo int32
	CargoFull    bool
	Cargo        string
	Route        *string
	UpdatedAt    time.Time
	TradeRoute   *string
}
