//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Systems struct {
	ID       string `sql:"primary_key"`
	SectorID string
	Type     string
	X        int32
	Y        int32
	Gid      int32
	Geom     string
}
