//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type TradingFleets struct {
	ID        string `sql:"primary_key"`
	SystemID  string
	StartTime time.Time
	Revenue   int64
	Expanses  int64
	Ships     *string
	UpdatedAt time.Time
}
