//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Transactions struct {
	ID           int32 `sql:"primary_key"`
	Waypoint     string
	Product      string
	Amount       int32
	Type         string
	Ship         string
	PricePerUnit int32
	TotalPrice   int32
	Timestamp    time.Time
	AgentBalance int64
}
