//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type WaypointsGraphs struct {
	ID       int32 `sql:"primary_key"`
	Source   int32
	Target   int32
	Cost     int32
	SystemID string
}
