//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Waypoints struct {
	ID                string `sql:"primary_key"`
	SystemID          string
	X                 int32
	Y                 int32
	Type              string
	Faction           string
	Orbits            *string
	UnderConstruction bool
	SubmittedOn       *time.Time
	SubmittedBy       *string
	Gid               int32
	Geom              string
}
