//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type WaypointsProducts struct {
	WaypointID string `sql:"primary_key"`
	ProductID  string `sql:"primary_key"`
	Export     bool
	Exchange   bool
	Import     bool
}
