//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type WaypointsModifiers struct {
	ModifierID string `sql:"primary_key"`
	WaypointID string `sql:"primary_key"`
}
