//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Modifiers = newModifiersTable("public", "modifiers", "")

type modifiersTable struct {
	postgres.Table

	// Columns
	ID postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type ModifiersTable struct {
	modifiersTable

	EXCLUDED modifiersTable
}

// AS creates new ModifiersTable with assigned alias
func (a ModifiersTable) AS(alias string) *ModifiersTable {
	return newModifiersTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ModifiersTable with assigned schema name
func (a ModifiersTable) FromSchema(schemaName string) *ModifiersTable {
	return newModifiersTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ModifiersTable with assigned table prefix
func (a ModifiersTable) WithPrefix(prefix string) *ModifiersTable {
	return newModifiersTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ModifiersTable with assigned table suffix
func (a ModifiersTable) WithSuffix(suffix string) *ModifiersTable {
	return newModifiersTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newModifiersTable(schemaName, tableName, alias string) *ModifiersTable {
	return &ModifiersTable{
		modifiersTable: newModifiersTableImpl(schemaName, tableName, alias),
		EXCLUDED:       newModifiersTableImpl("", "excluded", ""),
	}
}

func newModifiersTableImpl(schemaName, tableName, alias string) modifiersTable {
	var (
		IDColumn       = postgres.StringColumn("id")
		allColumns     = postgres.ColumnList{IDColumn}
		mutableColumns = postgres.ColumnList{}
	)

	return modifiersTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID: IDColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
