//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Factions = newFactionsTable("public", "factions", "")

type factionsTable struct {
	postgres.Table

	// Columns
	ID postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type FactionsTable struct {
	factionsTable

	EXCLUDED factionsTable
}

// AS creates new FactionsTable with assigned alias
func (a FactionsTable) AS(alias string) *FactionsTable {
	return newFactionsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new FactionsTable with assigned schema name
func (a FactionsTable) FromSchema(schemaName string) *FactionsTable {
	return newFactionsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new FactionsTable with assigned table prefix
func (a FactionsTable) WithPrefix(prefix string) *FactionsTable {
	return newFactionsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new FactionsTable with assigned table suffix
func (a FactionsTable) WithSuffix(suffix string) *FactionsTable {
	return newFactionsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newFactionsTable(schemaName, tableName, alias string) *FactionsTable {
	return &FactionsTable{
		factionsTable: newFactionsTableImpl(schemaName, tableName, alias),
		EXCLUDED:      newFactionsTableImpl("", "excluded", ""),
	}
}

func newFactionsTableImpl(schemaName, tableName, alias string) factionsTable {
	var (
		IDColumn       = postgres.StringColumn("id")
		allColumns     = postgres.ColumnList{IDColumn}
		mutableColumns = postgres.ColumnList{}
	)

	return factionsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID: IDColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
